# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

services:
  app:
    image: node:22
    volumes:
      - ./:/code
    working_dir: /code
    command: sh -c "test -d node_modules || npm install; npm run start"
    ports:
      - "${APP_PORT}:8998"
    tty: true

  frontend:
    container_name: wcstore_frontend
    image: ghcr.io/noi-techpark/opendatahub-webcomponent-store/opendatahub-webcomponent-store-local-wcs-frontend:latest
    environment:
      HOST: 0.0.0.0
    env_file: .env
    ports:
      - "${FRONTEND_PORT}:80"
    tty: true

  api:
    container_name: wcstore_api
    image: ghcr.io/noi-techpark/opendatahub-webcomponent-store/opendatahub-webcomponent-store-local-wcs-api:latest
    volumes:
      - ./workspace:/workspace
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "${API_SERVER_PORT}:${API_SERVER_PORT}"
    tty: true
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  cdn:
    container_name: wcstore_cdn
    image: ghcr.io/noi-techpark/opendatahub-webcomponent-store/opendatahub-webcomponent-store-local-wcs-cdn:latest
    volumes:
      - ./workspace:/workspace
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "${CDN_SERVER_PORT}:${CDN_SERVER_PORT}"
    tty: true
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  postgres:
    container_name: wcstore_postgres
    image: postgres:17
    ports:
      - "${PSQL_PORT}:5432"
    environment:
      POSTGRES_USER: wcs
      POSTGRES_PASSWORD: wcs
      POSTGRES_DB: wcs

  wcstore-cli:
    container_name: wcstore-cli
    image: ghcr.io/noi-techpark/opendatahub-webcomponent-store/opendatahub-webcomponent-store-local-wcs-cli:latest
    env_file: .env
    command: ./wait-for -t 0 api:${API_SERVER_PORT} -- python webcompstore-cli.py --push ${WC_VERSION}
    depends_on:
      - api
    volumes:
      - ./:/webcomponent
