version = 1
SPDX-PackageName = "webcomp-boilerplate"
SPDX-PackageSupplier = "NOI Techpark <digital@noi.bz.it>"
SPDX-PackageDownloadLocation = "https://github.com/noi-techpark/webcomp-boilerplate"

[[annotations]]
path = [".github/**", ".gitignore", "LICENSE.md", ".pre-commit-config.yaml", "**.json", ".editorconfig", ".env.example", "wcs-logo.png"]
precedence = "aggregate"
SPDX-FileCopyrightText = "(c) NOI Techpark <digital@noi.bz.it>"
SPDX-License-Identifier = "CC0-1.0"
